trigger:
  branches:
    include:
    - feature/*
    - hotfix/*
    - master
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml

schedules:
  - cron: "0 0 * * Sat"
    displayName: Weekly nightly CI
    branches:
      include:
        - master
    always: true

resources:
  repositories:
    - repository: templates
      type: git
      name: 'Composants partagés Forem/devops-java-ci-templates'
      ref: refs/heads/release/v3

stages:
  - template: template.yaml@templates
    parameters:
      projectName: java-yaml-properties-source-shared
      containsShareable: true
      mavenMainTaskOptions: '-DfailIfNoTests=false'
      alwaysRunSonar: true
      sonarType: 'SonarCloud'
      dependenciesUpdateConfig:
        enabled: true
        targetBranch: master