trigger:
  branches:
    include:
    - feature/*
    - hotfix/*
    - master
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml

schedules:
  - cron: "0 0 * * Sat"
    displayName: Weekly nightly CI
    branches:
      include:
        - master
    always: true

variables:
  - group: 'test-rnskvn'

resources:
  repositories:
    - repository: templates
      type: git
      name: 'Composants partagés Forem/devops-java-ci-templates'
      ref: refs/heads/release/v3

stages:
  - template: templates/push-to-external-host.template.yaml@templates
    parameters:
      gitRepoHostName: $(gitrepo.hostname)
      gitRepoBranchName: ${{ variables.shortBranchName }}
      gitRepoShortName: $(gitrepo.shortname)
      gitRepoUrl: $(gitrepo.url)